DROP TABLE IF EXISTS student; 
DROP TABLE IF EXISTS class; 

CREATE TABLE IF NOT EXISTS student(
 	 SID INT NOT NULL,
 	 `name` VARCHAR(50) NOT NULL,
 	 `gender` VARCHAR(10) CHECK (gender IN('male','female')),
 	 CID INT NOT NULL,
 	 PRIMARY KEY (SID) 	 
);

CREATE TABLE IF NOT EXISTS class(
 	CID INT NOT NULL,
 	SID INT NOT NULL,
 	comeTime DATETIME NOT NULL,
 	PRIMARY KEY(CID),
 	FOREIGN KEY (SID) REFERENCES student(SID) ON UPDATE CASCADE ON DELETE CASCADE 
);
